# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ahlyab\CODSOFT\Python\Task 5 - Quiz App\quiz_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(40, 80, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.option1 = QtWidgets.QRadioButton(self.centralwidget)
        self.option1.setGeometry(QtCore.QRect(50, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option1.setFont(font)
        self.option1.setObjectName("option1")
        self.option2 = QtWidgets.QRadioButton(self.centralwidget)
        self.option2.setGeometry(QtCore.QRect(50, 180, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option2.setFont(font)
        self.option2.setObjectName("option2")
        self.option3 = QtWidgets.QRadioButton(self.centralwidget)
        self.option3.setGeometry(QtCore.QRect(50, 230, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option3.setFont(font)
        self.option3.setObjectName("option3")
        self.option4 = QtWidgets.QRadioButton(self.centralwidget)
        self.option4.setGeometry(QtCore.QRect(50, 280, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option4.setFont(font)
        self.option4.setObjectName("option4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 310, 75, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz App"))
        self.label.setText(_translate("MainWindow", "Quiz App"))
        self.question.setText(_translate("MainWindow", "QuestionStatement"))
        self.option1.setText(_translate("MainWindow", "option1"))
        self.option2.setText(_translate("MainWindow", "option2"))
        self.option3.setText(_translate("MainWindow", "option3"))
        self.option4.setText(_translate("MainWindow", "option4"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
