# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ahlyab\CODSOFT\Python\Task 3 - Password Generator\password_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(264, 269)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.label.setObjectName("label")
        self.selector = QtWidgets.QSpinBox(self.centralwidget)
        self.selector.setGeometry(QtCore.QRect(170, 30, 51, 22))
        self.selector.setMinimum(8)
        self.selector.setMaximum(32)
        self.selector.setObjectName("selector")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(100, 80, 75, 24))
        self.generate.setObjectName("generate")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(30, 130, 191, 21))
        self.output.setObjectName("output")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(80, 170, 111, 24))
        self.copy.setObjectName("copy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 264, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.label.setText(_translate("MainWindow", "Select password length"))
        self.generate.setText(_translate("MainWindow", "Generate"))
        self.copy.setText(_translate("MainWindow", "copy to clipboard"))
